# -*- coding: utf-8 -*-
"""Sales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adjXVlXXG81PO_lhEDWcejE2VJSg-9gg

# **IMS**
## *Inventory Management System*

TO Sale PRODUCT from INVENTORY
"""

from datetime import *

import json

f= open("records.json","r")
readata = f.read()
records = json.loads(readata)
f.close()
ids =[]

print("<--------------------Our Catelog!-----------------------------> \n \n")
for j in records.keys():
  print("Product Id : ",j)
  i = records[j]
  print("Name : ",i["name"])
  print("Quantity : ",i["quantity"])
  print("Price : ",i["Price"])
  print("Category : ",i["Category"])
  print("Weight : ",i["Weight"])
  print("\n <--------------------------------------------------------------------> \n")

nsell = int(input("How many product you want to buy! : "))

for i in range(nsell):
  id = input("Enter the "+str(i+1)+"th Product Id! ")
  if id not in records:
    print("Invalid Id! or Product not Found")
  else :
    ids.append(id)

c_sale = []

for item in ids:
  n = int(input("How many Quantity of "+records[item]['name']+" you want to buy : "))
  if records[item]['quantity'] < n:
    print("Invalid Quatity or Out of Stock \n Try lesser value next time!")
    continue
  pp = records[item]['Price']*n
  choice = input("Do you want to buy "+str(n)+" "+records[item]['name']+" for INR "+str(pp)+" \n Say Y/N : ")
  if(choice.lower() == "n"):
    print("Your this Cart product is Removed!")
    continue
  records[item]['quantity'] -= n
  print("You bought ",n," ",records[item]['name'],"for INR",pp," Successfully")
  print("\n <--------------------------------------------------------------------> \n")
  c_sale.append({"name":records[item]['name'],"quantity":n,"total":pp})


sales_reader_file = open("Sales.json","r")
sales_reader = json.loads(sales_reader_file.read())
sales_reader_file.close()
saver = open("Sales.json","w")
sales_len = len(sales_reader)

sales_reader[str(sales_len)]={"date":str(datetime.now()),"items":c_sale}
sjson = json.dumps(sales_reader)
saver.write(sjson)
saver.close()


